# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# MY NOTE: These variables are included in all other sections below. You can
# override any variable here by redefining it in the desired section. However,
# we advise against this. Our practice is to try and use these secrets as just
# proxies to environment variables as much as possible, and not as hard-coded
# values.
# Then why have this at all, why not read values directly from `ENV['XYZ']`?
# Because we want to provide as much flexibility as possible to the developer,
# by abstracting away the underlying value store, yet keeping a single point of
# access, i.e. `Rails.secrets.xyz`.
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_app_base_urls: <%= ENV["CLIENT_APP_BASE_URLS"] %>
  # AWS info (for AWS integration, for example for the media library)
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  aws_cf_key_pair_id: <%= ENV["AWS_CF_KEY_PAIR_ID"] %>
  aws_cf_private_key: <%= ENV["AWS_CF_PRIVATE_KEY"] %>
  aws_cf_distribution_id: <%= ENV["AWS_CF_DISTRIBUTION_ID"] %>

development:
  <<: *defaults

test:
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
